### ISSUE TITLE
Error When running Maven

### ISSUE THREAD

**Issue by Tlturner77** [chrisdolan/wireshark-opus#1]
When running Maven I am getting the following issue:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0

**Comment by chrisdolan** [comment]
Just based on that error message, that sounds like a Maven problem, not a problem with my code. To check that theory, could you try loading a different project with Maven to see if it happens elsewhere?

And when I see class version, it often is related to using the wrong JDK version. What version do you have?

**Comment by Tlturner77** [comment]
running java --version I get the following. 

javac 1.6.0_65

I don't have any other maven projects to run otherwise I would try that.
